import fs from 'node:fs/promises';
import path from 'node:path';

const projectRoot = process.cwd();
const envPath = path.join(projectRoot, '.env');
const outPath = path.join(projectRoot, 'src', 'env.ts');

function parseDotEnv(text) {
  const lines = text.split(/\r?\n/);
  const out = {};
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const idx = line.indexOf('=');
    if (idx === -1) continue;

    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();

    const isQuoted =
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"));

    // Support common .env inline comments: KEY=value # comment
    // Only strip when the value is NOT quoted.
    if (!isQuoted) {
      value = value.replace(/\s[;#].*$/, '').trim();
    } else {
      value = value.slice(1, -1);
    }

    out[key] = value;
  }
  return out;
}

const raw = await fs.readFile(envPath, 'utf8');
const parsed = parseDotEnv(raw);

const keys = [
  'VITE_APP_CLIENT_ID',
  'VITE_AUTHORITY',
  'VITE_KNOWN_AUTHORITIES',
  'VITE_REDIRECT_URI',
  'VITE_POST_LOGOUT_REDIRECT_URI',
  'VITE_CACHE_LOCATION',
  'VITE_PASSWORD_RESET_AUTHORITY',
  'VITE_B2C_SCOPES',
];

const payload = {};
for (const k of keys) {
  if (parsed[k] !== undefined) payload[k] = parsed[k];
}

const file =
  `// This file is generated by scripts/generate-env.mjs\n` +
  `// Do not edit manually.\n` +
  `export const env = ${JSON.stringify(payload, null, 2)} as const;\n`;

await fs.mkdir(path.dirname(outPath), { recursive: true });
await fs.writeFile(outPath, file, 'utf8');

console.log(`Generated ${path.relative(projectRoot, outPath)}`);
